### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by steven-murray** [telegraphic/pygdsm#1]
There doesn't seem to be a license on the repo. Can I strongly recommend _not_ using GPL as pygsm did? It's a copy-left license which forces code that imports it to also use GPL (which is sometimes not an option, and hence they can't use pygsm). MIT or BSD would be great, if that suits you.

**Comment by telegraphic** [comment]
Hi @steven-murray I always intended for the code to be MIT -- license in `README.md` should have reflected that? I can add a LICENSE file too though

**Comment by telegraphic** [comment]
Ok I've added an explicit `LICENSE` file, so closing this issue, cheers 🍻
