### ISSUE TITLE
pygsm mnodule not found error

### ISSUE THREAD

**Issue by torishabhmehta** [telegraphic/pygdsm#10]
In the quickstart notebook, the module imports are for pygsm, and not pygdsm. The pygsm import fails, but pygdsm import works.

**Comment by telegraphic** [comment]
Thanks @torishabhmehta , this is a hangover from when pygdsm was called pygsm. I changed the name as there was already a package (for a GSM modem) called pygsm.

**Comment by telegraphic** [comment]
Finally updated!
