### ISSUE TITLE
Bug in masking entries below the horizon

### ISSUE THREAD

**Issue by christophwelling** [telegraphic/pygdsm#3]
I think the GSMObserver does not mask entries below the horizon correctly. In line 68 of base_observer.py, self._phi is used to mask entries, but this should be self._theta.

**Comment by telegraphic** [comment]
Thanks @christophwelling, interesting! It's been a while since I looked at that code, will revisit it when I get a chance. (pull requests welcome of course).

**Comment by christophwelling** [comment]
I'll be happy do make a pull request. Can you please give me permission to push a new branch into the repo?

**Comment by telegraphic** [comment]
sure thing, invite waiting!

**Comment by cdilullo** [comment]
@telegraphic If this is still an open problem, I think I've come up with a solution which creates the horizon mask by computing the haversine distance between zenith and all points on the sky and then masking all points that are > 90 deg away. I'll submit a pull request if you can give me permission to push to the repo

**Comment by telegraphic** [comment]
Thanks @cdilullo, this looks to work and makes sense! Closing 🥇
